// Builds the full icon set from the chosen brand mark (branding/lectern-mark-1.jpg,
// generated by scripts/generate-logo.mjs): `node scripts/make-icons.mjs`
//   → extension/icons/icon{16,32,48,128}.png   (full-bleed rounded cream tile)
//   → build/icon.png (1024, macOS-style inset rounded tile on transparency)
//   → public/icons/favicon.png (48)
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import puppeteer from 'puppeteer-core';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const CHROME =
  process.env.CHROME_PATH ?? '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';

const MARK = path.join(root, 'branding', 'lectern-mark-1.jpg');
const markUri = `data:image/jpeg;base64,${readFileSync(MARK).toString('base64')}`;

// zoom crops the source's generous margins so the mark reads at small sizes
const tile = (size, { radiusPct, insetPct = 0, zoomPct = 155 }) => {
  const inner = Math.round(size * (1 - insetPct / 100));
  const offset = Math.round((size - inner) / 2);
  return `<!DOCTYPE html>
<html><head><style>
  html, body { margin: 0; padding: 0; background: transparent; }
  .tile {
    position: absolute; left: ${offset}px; top: ${offset}px;
    width: ${inner}px; height: ${inner}px;
    border-radius: ${Math.round((inner * radiusPct) / 100)}px;
    background-color: #f4eee1;
    background-image: url("${markUri}");
    background-size: ${zoomPct}% ${zoomPct}%;
    background-position: center 42%;
    background-repeat: no-repeat;
  }
</style></head><body><div class="tile"></div>
<img id="probe" src="${markUri}" style="position:absolute;visibility:hidden;width:1px;height:1px">
</body></html>`;
};

mkdirSync(path.join(root, 'extension', 'icons'), { recursive: true });
mkdirSync(path.join(root, 'build'), { recursive: true });
mkdirSync(path.join(root, 'public', 'icons'), { recursive: true });

const targets = [
  ...[16, 32, 48, 128].map((size) => ({
    size,
    file: path.join(root, 'extension', 'icons', `icon${size}.png`),
    opts: { radiusPct: 22 },
  })),
  // macOS Big Sur convention: tile occupies ~81% of the canvas, corners ~22.5%
  {
    size: 1024,
    file: path.join(root, 'build', 'icon.png'),
    opts: { radiusPct: 22.5, insetPct: 19 },
  },
  {
    size: 48,
    file: path.join(root, 'public', 'icons', 'favicon.png'),
    opts: { radiusPct: 22 },
  },
];

const browser = await puppeteer.launch({ executablePath: CHROME, headless: 'new' });
try {
  const page = await browser.newPage();
  for (const { size, file, opts } of targets) {
    await page.setViewport({ width: size, height: size, deviceScaleFactor: 1 });
    await page.setContent(tile(size, opts));
    await page.waitForFunction(() => document.getElementById('probe')?.complete, { timeout: 15_000 });
    await page.evaluate(() => document.getElementById('probe').decode().catch(() => {}));
    const buf = await page.screenshot({
      omitBackground: true,
      clip: { x: 0, y: 0, width: size, height: size },
    });
    writeFileSync(file, buf);
    console.log(`wrote ${path.relative(root, file)} (${size}×${size})`);
  }
} finally {
  await browser.close();
}
